version: '3.8'

services:
  file-shifter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: file-shifter
    restart: unless-stopped
    
    # Environment-Variablen - diese sollten durch externe .env-Datei oder Secrets gesetzt werden
    environment:
      # Logging
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      
      # Input-Directory
      - INPUT=${INPUT:-/app/input}
      
      # Output-Targets (bis zu 10 konfigurierbar)
      - OUTPUTS_1_PATH=${OUTPUTS_1_PATH}
      - OUTPUTS_1_TYPE=${OUTPUTS_1_TYPE}
      - OUTPUTS_2_PATH=${OUTPUTS_2_PATH}
      - OUTPUTS_2_TYPE=${OUTPUTS_2_TYPE}
      - OUTPUTS_3_PATH=${OUTPUTS_3_PATH}
      - OUTPUTS_3_TYPE=${OUTPUTS_3_TYPE}
      - OUTPUTS_4_PATH=${OUTPUTS_4_PATH}
      - OUTPUTS_4_TYPE=${OUTPUTS_4_TYPE}
      - OUTPUTS_5_PATH=${OUTPUTS_5_PATH}
      - OUTPUTS_5_TYPE=${OUTPUTS_5_TYPE}
      
      # S3-Konfiguration
      - OUTPUT_CONFIG_S3_ENDPOINT=${OUTPUT_CONFIG_S3_ENDPOINT}
      - OUTPUT_CONFIG_S3_ACCESS_KEY=${OUTPUT_CONFIG_S3_ACCESS_KEY}
      - OUTPUT_CONFIG_S3_SECRET_KEY=${OUTPUT_CONFIG_S3_SECRET_KEY}
      - OUTPUT_CONFIG_S3_REGION=${OUTPUT_CONFIG_S3_REGION:-us-east-1}
      
      # FTP/SFTP-Konfiguration
      - OUTPUT_CONFIG_FTP_HOST=${OUTPUT_CONFIG_FTP_HOST}
      - OUTPUT_CONFIG_FTP_USERNAME=${OUTPUT_CONFIG_FTP_USERNAME}
      - OUTPUT_CONFIG_FTP_PASSWORD=${OUTPUT_CONFIG_FTP_PASSWORD}
    
    # Volumes
    volumes:
      - ${HOST_INPUT_DIR:-./input}:/app/input
      - ${HOST_OUTPUT_DIR:-./output}:/app/output
      - ${HOST_CONFIG_DIR:-./config}:/app/config:ro
    
    # Resource-Limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.1'
    
    # Logging-Konfiguration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Health-Check
    healthcheck:
      test: ["CMD", "ps", "aux", "|", "grep", "[m]ain"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s