# Beispiel für ENV-basierte Konfiguration
services:
  file-shifter:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: file-shifter
    restart: unless-stopped
    
    # Environment-Variablen aus .env-Datei laden
    env_file:
      - .env
    
    # Zusätzliche Container-spezifische Umgebungsvariablen
    environment:
      # Überschreibt .env falls nötig
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      INPUT: ${INPUT:-/app/input}
    
    # Volumes
    volumes:
      - ${HOST_INPUT_DIR:-./input}:/app/input
      - ${HOST_OUTPUT_DIR:-./output}:/app/output
      - ${HOST_CONFIG_DIR:-./config}:/app/config:ro
    
    # Netzwerk
    networks:
      - file-shifter-network

# Beispiel .env-Datei Inhalt:
# LOG_LEVEL=INFO
# INPUT=/app/input
# OUTPUT_1_PATH=/app/output1
# OUTPUT_1_TYPE=filesystem
# OUTPUT_2_PATH=s3://my-bucket/files
# OUTPUT_2_TYPE=s3
# OUTPUT_2_ENDPOINT=minio:9000
# OUTPUT_2_ACCESS_KEY=minioadmin
# OUTPUT_2_SECRET_KEY=minioadmin
# OUTPUT_2_SSL=false
# OUTPUT_2_REGION=eu-central-1
# HOST_INPUT_DIR=./input
# HOST_OUTPUT_DIR=./output
# HOST_CONFIG_DIR=./config

networks:
  file-shifter-network:
    driver: bridge